### ISSUE TITLE
Document prove program

### ISSUE THREAD

**Issue by jgarte** [chneukirchen/xe#12]
Hi,

What is this prove program that is executed during the `check` target?

https://github.com/leahneukirchen/xe/blob/master/Makefile#L18

**Comment by leahneukirchen** [comment]
It's a program included with Perl, https://linux.die.net/man/1/prove

**Comment by jgarte** [comment]
Thanks for the info. 

TIL:
```
$ guix locate prove
perl@5.36.0          /gnu/store/v6bivyjbg6bj07s8iqfzdm6hpvypc0p1-perl-5.36.0/bin/prove
```
