### ISSUE TITLE
Execution stops for some exit codes but not others

### ISSUE THREAD

**Issue by whiteinge** [chneukirchen/xe#6]
`xe` prematurely stops execution for select exit codes, as though the `-F` flag was given.

Expected behavior (execution continues past bar):
```
% printf '%s\n' foo bar baz | xe -s 'if [ $1 = bar ]; then exit 1; else touch $1; fi'
% lr foo bar baz
lr: cannot lstat 'bar': No such file or directory
baz
foo
```

Unexpected behavior (execution stops at bar):
```
% printf '%s\n' foo bar baz | xe -s 'if [ $1 = bar ]; then exit 128; else touch $1; fi'
% lr foo bar baz
lr: cannot lstat 'bar': No such file or directory
lr: cannot lstat 'baz': No such file or directory
foo
```

I noticed this when automating Git invocations, since it will return 128 when run outside a repo. I haven't tested other exit codes.

**Comment by leahneukirchen** [comment]
Good point, GNU xargs says

>               123    if any invocation of the command exited with status 1-125

but e.g. OpenBSD xargs says

>            123     One or more invocations of utility returned a nonzero exit status.

And actually GNU xargs behaves like OpenBSD xargs.

So xe should work this way too I think.

**Comment by leahneukirchen** [comment]
However OpenBSD xargs maps 126 and 127 in the child to the parent, always.

**Comment by leahneukirchen** [comment]
A proper solution to this requires checking if the exec really worked, which will need some restructuring.  Thanks for finding this!

**Comment by whiteinge** [comment]
Oh, yikes, the GNU/BSD difference is interesting (and annoying). And, of course, [POSIX has a similar yet slightly different take](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html) as well. 😕 

Sticking with BSD behavior works for me, FWIW. Either way, TIL I need to pay much more attention to my exit codes with both xargs and xe 😀 .

**Comment by leahneukirchen** [comment]
Please try the linked PR #7, it's not too hard to do this properly.
